[package]
name = "herfavesenpai/senpai-fw"
description = "a game framework written by herfavesenpai"
version = "0.0.2"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
Knit = "sleitnick/knit@*"
Component = "sleitnick/component@*"
EnumList = "sleitnick/enum-list@*"
Option = "sleitnick/option@*"
Signal = "sleitnick/signal@*"
Comm = "sleitnick/comm@*"
TableUtil = "sleitnick/table-util@*"
Timer = "sleitnick/timer@*"
Trove = "sleitnick/trove@*"
Streamable = "sleitnick/streamable@*"
comm = "sleitnick/comm@*"
Promise = "evaera/promise@*"
gooey-particles = "passhley/gooey-particles@*"
Maid = "howmanysmall/janitor@*"
Fusion = "elttob/fusion@0.1.1-beta"
LuaEnum = "corecii/lua-enum-simple@0.1.0"
WaitFor = "sleitnick/wait-for@0.2.1"
Janitor = "howmanysmall/janitor@^1.14.1"

[server-dependencies]
Cmdr = "evaera/cmdr@1.9.0"